# Generated by Django 4.1.2 on 2022-11-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_category_subscribers_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
